MusicBrainzDemo/Models/Search/SearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicBrainzDemo.Models.Search
{
    public class SearchModel
    {
    }
}

MusicBrainzDemo/ViewModels/Search/SearchViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicBrainzDemo.ViewModels.Search
{
    public class SearchViewModel
    {
        [Required] 
        [Display(Name = "Artist name")]
        public string ArtistName { get; set; }
    }
}

MusicBrainzDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MusicBrainzDemo.Controllers
{
    public class HomeController : Controller
    {        
        public ActionResult Index()
        {
            // Get MusicBrainz access token from URL query 
            string accessToken = Request.QueryString["code"];


            // If access token exists store it
            if (accessToken != null)
            {
                MusicBrainzDemo.Helpers.LoginHelper.SetLoggedIn(accessToken);
            }            

            return View();
        }
    }
}

MusicBrainzDemo/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;

namespace MusicBrainzDemo.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        // Handle the logout link
        public ActionResult Logout()
        {
            MusicBrainzDemo.Helpers.LoginHelper.RemoveSession();
            return RedirectToAction("Index", "Home");
        }

        // Fetch content from MusicBrainz login page
        private HttpResponseMessage MusicBrainz_Authenticate()
        {
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
                                                   | SecurityProtocolType.Tls11
                                                   | SecurityProtocolType.Tls12
                                                   | SecurityProtocolType.Ssl3;
            
            // Setup url to reach MusicBrainz authetincation page
            string html = String.Empty;
            string url = "http://" + HttpContext.Request.Url.Host + ":" + HttpContext.Request.Url.Port;
            StringBuilder sbUrl = new StringBuilder();

            sbUrl.Append("https://musicbrainz.org/oauth2/authorize?");
            sbUrl.Append("client_id=mJAE1ZhAnqLnC3Pg6Hnt9Q85V0PA-Qgo&");
            sbUrl.Append("response_type=code&");
            sbUrl.Append("redirect_uri=" + url + "&");
            sbUrl.Append("grant_type=authorization_code&");
            sbUrl.Append("scope=profile");

            // Prepare web request
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(sbUrl.ToString());            
            using (HttpWebResponse webResponse = (HttpWebResponse)request.GetResponse())
            using (Stream stream = webResponse.GetResponseStream())
            using (StreamReader reader = new StreamReader(stream))
            {
                html = reader.ReadToEnd();
            }

            // Get response from authentication page
            var response = new HttpResponseMessage();
            response.Content = new StringContent(html);
            response.Content.Headers.ContentType = new MediaTypeHeaderValue("text/html");

            return response;
        }

        // Go to MusicBrainz webpage and authenticate
        public ContentResult AuthenticateToMusicBrainz()
        {
            string response = MusicBrainz_Authenticate().Content.ReadAsStringAsync().Result;
            return Content(response);
        }   
    }
}

MusicBrainzDemo/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.IO;
using System.Text;
using System.Net.Http;
using System.Web.Mvc;
using MusicBrainzDemo.ViewModels.Search;
using MusicBrainzDemo.Helpers;
using System.Web.Script.Serialization;


namespace MusicBrainzDemo.Controllers
{
    public class SearchController : Controller
    {       

        [HttpPost]
        // Search for an artist
        public string SearchArtist(SearchViewModel model)
        {
            if (model == null) return string.Empty;

            List<ArtistList> result = new MusicBrainzHelper().SearchArtist(model.ArtistName);

            string myJsonString = (new JavaScriptSerializer()).Serialize(result);            

            return myJsonString;
        }

        [HttpPost]
        // Search for songs given an artist
        public string SearchSongs(string artistID)
        {
            if (string.IsNullOrEmpty(artistID)) return string.Empty;

            List<SongList> result = new MusicBrainzHelper().SearchSongs(artistID);
                        
            string myJsonString = (new JavaScriptSerializer()).Serialize(result);

            return myJsonString;
        }
    }
}

MusicBrainzDemo/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>MusicBrainz Demo</h1>
    @if (!MusicBrainzDemo.Helpers.LoginHelper.IsLoggedIn())
    {
        <p class="lead">You will need to <a href="/Login">login </a> to use this.</p>
    }
    else
    {
        <p class="lead">Welcome</p>
    }
    
</div>

<!-- Need to login to use search -->
@if (MusicBrainzDemo.Helpers.LoginHelper.IsLoggedIn())
{
    @Html.Partial("_Main")
}

MusicBrainzDemo/Views/Login/Index.cshtml
<h2>Authenticate via MusicBrainz</h2>


@Html.ActionLink("Authenticate via MusicrBrainz", "AuthenticateToMusicBrainz", "Login", null, new { @class = "btn btn-primary btn-lg"})

MusicBrainzDemo/Views/Shared/_Layout.cshtml
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/Scripts/ChartJS/Chart.min.js")
@Scripts.Render("~/Scripts/ChartJS/utils.js")
@RenderSection("scripts", required: false)

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MusicBrainz Demo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MusicBrainz Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">     

                    <!-- Hide and show the login/logout appropriately -->
                    @if (MusicBrainzDemo.Helpers.LoginHelper.IsLoggedIn())
                    { 
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Index", "Login")</li>
                    }                    

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MusicBrainz Demo</p>
        </footer>
    </div>

</body>
</html>

MusicBrainzDemo/Views/Shared/_Main.cshtml
@using MusicBrainzDemo.ViewModels.Search
@model SearchViewModel

<strong>Welcome to MusicBrainz Demo</strong>
<br/>
<br/>

<script type='text/javascript'>
        
    var ctx = null; 
    var color = Chart.helpers.color;

    // These functions relate to the scatter plot
    

    // Generate scatter data
    function generateData() {
        var data = [];
        for (var i = 0; i < 7; i++) {
            data.push({
                x: randomScalingFactor(),
                y: randomScalingFactor()
            });
        }
        return data;
    }

    // Find words in a string
    function countWords(str) {
        return str.trim().split(/\s+/).length;
    }

    // Get all song titles 
    function getSongTitles() {
        var titles = [];

        // Get each title
        $("div#divSongResultList ul li").each(function (i) {
            titles.push($(this).find("a").text());
        });

        return titles;
    }     

    // Generate data with average length for each song title
    function generateAverage() {
        var data = [];
        var titles = getSongTitles();        
        var totalWordLength = 0;
        var average = 1, min = 1, max = 1, titleLength = 0;

        // Get some values from song titles
        for (var i = 0; i < titles.length - 1; i++) {

            // Get title length
            titleLength = countWords(titles[i]);
        
            // Get min, max and total word length
            (min = titleLength < min ? titleLength : min);
            (max = titleLength > max ? titleLength : max);
            totalWordLength += countWords(titles[i]);
        }

        // Get average word length
        averageWordLength = totalWordLength / titles.length;

        // Generate data from these values
        data.push({
            x: 0,
            y: min
        });

        data.push({
            x: 1,
            y: averageWordLength
        });

        data.push({
            x: 2,
            y: max
        });

        return data;
    }

    // Generate data with word length for each song title
    function generateWordLength() {
        var data = [];
        var titles = getSongTitles();
        
        // Generate data from word length for each title
        for (var i = 0; i < titles.length - 1; i++) {
            data.push({
                x: i,
                y: countWords(titles[i])
            });
        }

        return data;
    }

    // Setup scatter data structure
    var scatterChartData = {
        datasets: [{
            label: '',
            borderColor: window.chartColors.red,
            backgroundColor: color(window.chartColors.red).alpha(0.2).rgbString(),
            data: []
        }]
    };

    // Draw a scatter plot for average values
    function DrawScatterPlot_Average() {

        scatterChartData.datasets[0].label = 'Average title length';
        scatterChartData.datasets.forEach(function (dataset) {
            dataset.data = generateAverage();
        });
        window.myScatter.update();
    }

    // Draw a scatter plot for title word length
    function DrawScatterPlot_WordLength() {

        scatterChartData.datasets[0].label = 'Title word length';
        scatterChartData.datasets.forEach(function (dataset) {
            dataset.data = generateWordLength();
        });
        window.myScatter.update();

    }

    // Draw empty scatter plot
    function DrawEmptyPlot() {
        window.myScatter = Chart.Scatter(ctx, {
            data: scatterChartData,
            options: {
                title: {
                    display: true,
                    text: 'Scatter Chart'
                },
            }
        });
    }

    // Handle the selection of an artist
    function searchSongs(artistID) {

        $.ajax({
            url: '@Url.Action("SearchSongs", "Search")',
            datatype: 'JSON',
            type: 'POST',
            data: { 'artistID': artistID },
            success: function (data) {

                // Show song result
                $("#divSongResult").show();
                $("#divScatterPlot").show();

                // Show scatter plot
                DrawEmptyPlot();

                // If no results then exit
                if (jQuery.isEmptyObject(jQuery.parseJSON(data))) {
                    $("#divSongResultList").html("No result");
                    return;
                }

                // Prepare list with song results
                var songs = '<ul>';
                $.each(jQuery.parseJSON(data), function () {
                    songs += '<li> <a href="#" onclick="getLyricsStatistics(\'' + this["SongID"] + '\')">' + this["SongName"] + '</a></li>';
                })
                songs += '</ul>';

                // Display song result list
                $("#divSongResultList").html(songs);
            },
            error: function (error) {
                alert(error.responseText);
            }
        });

    }

    $(document).ready(function () {        

        // Get canvas div
        ctx = document.getElementById('canvas').getContext('2d');

        // Hide results
        $("#divArtistResult").hide();
        $("#divSongResult").hide();
        $("#divScatterPlot").hide();

        // Handle button click to show average number of words
        $("#btnAverage").click(function () {

            DrawScatterPlot_Average();

            // Stop callback
            return false;
        });

        // Handle button click to sort titles by length
        $("#btnWordLength").click(function () {

            DrawScatterPlot_WordLength();

            // Stop callback
            return false;
        });

        // Handle the search for artists
        $("#btnSearchArtist").click(function () {            

            $.ajax({
                url: $("#searchArtistForm").attr('action'),
                datatype: 'JSON',
                type: 'POST',
                data: $("#searchArtistForm").serialize(),               
                success: function (data) {

                    // Clear artist and song list
                    $("#divArtistResultList").html('');
                    $("#divSongResultList").html('');

                    // Hide song result
                    $("#divSongResult").hide();
                    $("#divScatterPlot").hide();

                    // Show artist result
                    $("#divArtistResult").show();                   

                    // If no results then exit
                    if (jQuery.isEmptyObject(jQuery.parseJSON(data))) {
                        $("#divArtistResultList").html("No result");
                        return;
                    }

                    // Prepare list with artist results
                    var artists = '<ul>';
                    $.each(jQuery.parseJSON(data), function () {
                        artists += '<li> <a href="#" onclick="searchSongs(\'' + this["ArtistID"] + '\')">' + this["ArtistName"] + '</a></li>';
                    })
                    artists += '</ul>';

                    // Display artist result list
                    $("#divArtistResultList").html(artists);
                },
                error: function (error) {
                    alert(error.responseText);
                }
            });

        });
    });
</script>

@using (Html.BeginForm("SearchArtist", "Search", FormMethod.Post, new { id = "searchArtistForm" }))
{

    @Html.LabelFor(m => m.ArtistName)
    <span>&nbsp;</span>
    @Html.TextBoxFor(m => m.ArtistName)
    <button id="btnSearchArtist" type="button">Search</button>
}
<br/>
        
<div id="divArtistResult">
    <strong>Artist search results</strong>
    <div id="divArtistResultList"></div>
</div>

<div id="divSongResult">

    <strong>Songs search results</strong>
    <div id="divSongResultList"></div>

</div>

<div id="divScatterPlot">
    <div style="width:75%">
        <canvas id="canvas"></canvas>
    </div>
    <table>
        <tr>
            <td><button id="btnWordLength">Show</button></td>
            <td>Plot length of words for each title</td>
        </tr>
        <tr>
            <td><button id="btnAverage">Show</button></td>
            <td>Plot min, max and average title length</td>
        </tr>
    </table>
</div>




    